### ISSUE TITLE
Missing liveness / readiness / startup probes

### ISSUE THREAD

**Issue by vasyan1992** [chatwoot/charts#151]
In helm chart probes are missing and at least for web-deployment it is needed to perform rollout restart without service interruption 
would be nice to be able to configure something like 
```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1

```
